### ISSUE TITLE
Get a pointer of the Mat data is incomplete?

### ISSUE THREAD

**Issue by ymtoo** [stereolabs/zed-c-api#3]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

The following is the only c api to get a pointer of the Mat data.
```
INTERFACE_API int* sl_mat_get_ptr(int* ptr, enum SL_MEM mem) {
        return (int*) MAT->getPtr<sl::uchar1>((sl::MEM)(mem + 1));
    }
```
As compared to ZED Python API, most of these functions 
```
char1 *getPointerUchar1(Mat &mat, MEM memory_type)
uchar2 *getPointerUchar2(Mat &mat, MEM memory_type)
uchar3 *getPointerUchar3(Mat &mat, MEM memory_type)
uchar4 *getPointerUchar4(Mat &mat, MEM memory_type)
ushort1 *getPointerUshort1(Mat &mat, MEM memory_type)

float1 *getPointerFloat1(Mat &mat, MEM memory_type)
float2 *getPointerFloat2(Mat &mat, MEM memory_type)
float3 *getPointerFloat3(Mat &mat, MEM memory_type)
float4 *getPointerFloat4(Mat &mat, MEM memory_type)
```
are probably missing.

### Steps to Reproduce

na

### Expected Result

na

### Actual Result

na

### ZED Camera model

ZED2

### Environment

```shell
ZED SDK 3.7
```

**Comment by torkeldanielsson** [comment]
Just cast it? This is C after all :)

..but yeah, for completeness I guess it could make sense.
